apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: u2jc3km7s-nodejs 
  janus-idp.io/tekton: u2jc3km7s-nodejs
  backstage.io/kubernetes-id: u2jc3km7s-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: u2jc3km7s-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml